feat: added .() root - added 'case' support

diff --git a/scrippo b/scrippo
--- a/scrippo
+++ b/scrippo
@@ -78,9 +78,10 @@ function ast_statement {
   local orphan_re='^(elif|else)([[:space:]]|$)'
   local for_re='^for[[:space:]]+([a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]+in[[:space:]]+(.+)$'
   local while_re='^while[[:space:]]+(.+)$'
+  local case_re='^case[[:space:]]+(.+)$'
   local echo_re='^->[[:space:]]*(.*)$'
   local macro_re='^@([a-zA-Z_][a-zA-Z0-9_]*)([[:space:]]+(.*))?$'
-  local function_re='^\.?[a-zA-Z_][a-zA-Z0-9_]*\('
+  local function_re='^(\.|\.?[a-zA-Z_][a-zA-Z0-9_]*)\('
   local declaration_re='^([a-zA-Z_][a-zA-Z0-9_]*)<([^>]*)>$'
   local typed_assignment_re='^([a-zA-Z_][a-zA-Z0-9_]*)<([^>]*)>[[:space:]]*=[[:space:]]*(.*)$'
   local assignment_re='^([a-zA-Z_][a-zA-Z0-9_]*)=(.*)$'
@@ -93,6 +94,8 @@ function ast_statement {
     ast_for "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
   elif [[ $_ast_text =~ $while_re ]]; then
     ast_while "${BASH_REMATCH[1]}"
+  elif [[ $_ast_text =~ $case_re ]]; then
+    ast_case "${BASH_REMATCH[1]}"
   elif [[ $_ast_text =~ $echo_re ]]; then
     ast_next
     ast_echo "${BASH_REMATCH[1]}"
@@ -177,6 +180,76 @@ function ast_while {
   ast_next
   ast_block "$indent"
   _ast_result=$(jq -nc --argjson condition "$condition" --argjson body "$_ast_result" '{type: "while", condition: $condition, body: $body}')
+}
+
+function ast_case {
+  local indent=$_ast_indent subject=${1%[[:space:]]in} arms=()
+  subject=${subject%"${subject##*[![:space:]]}"}
+  ast_next
+  while ast_peek && (( _ast_indent > indent )); do
+    ast_case_arm
+    arms+=("$_ast_result")
+  done
+  ast_list "${arms[@]}"
+  _ast_result=$(jq -c --arg subject "$subject" '{type: "case", subject: $subject, arms: .}' <<< "$_ast_result")
+}
+
+function ast_case_arm {
+  local indent=$_ast_indent text=$_ast_text pattern="" quote="" depth=0 char i
+  local rest lead terminator=";;" inline="" body last
+  local terminated_re='^(.*[^;])?(;;&|;;|;&)$'
+  local terminator_re='^(;;&|;;|;&)$'
+  if [[ $text =~ $terminator_re ]]; then
+    ast_error "unexpected '$text': end the arm's line with it or indent it under the arm"
+  fi
+  for (( i=0; i<${#text}; i++ )); do
+    char=${text:i:1}
+    if [[ -n $quote ]]; then
+      [[ $char == "$quote" ]] && quote=""
+    elif [[ $char == [\"\'] ]]; then
+      quote=$char
+    elif [[ $char == "(" ]]; then
+      depth=$(( depth + 1 ))
+    elif [[ $char == ")" ]] && (( depth == 0 )); then
+      break
+    elif [[ $char == ")" ]]; then
+      depth=$(( depth - 1 ))
+    fi
+    pattern+=$char
+  done
+  if [[ -z $pattern ]] || (( i == ${#text} )); then
+    ast_error "expected 'pattern)' in case, got '$text'"
+  fi
+
+  rest=${text:i+1}
+  lead=${rest%%[![:space:]]*}
+  rest=${rest#"$lead"}
+  if [[ $rest =~ $terminated_re ]]; then
+    rest=${BASH_REMATCH[1]}
+    terminator=${BASH_REMATCH[2]}
+  fi
+  rest=${rest%"${rest##*[![:space:]]}"}
+
+  if [[ -n $rest ]]; then
+    _ast_text=$rest
+    _ast_indent=$(( indent + i + 1 + ${#lead} ))
+    ast_statement
+    inline=$_ast_result
+  else
+    ast_next
+  fi
+
+  ast_block "$indent"
+  body=$_ast_result
+  if [[ -n $inline ]]; then
+    body=$(jq -c --argjson inline "$inline" '[$inline] + .' <<< "$body")
+  fi
+  last=$(jq -r '.[-1] | select(.type == "bash") | .raw' <<< "$body")
+  if [[ $last =~ $terminator_re ]]; then
+    terminator=$last
+    body=$(jq -c '.[:-1]' <<< "$body")
+  fi
+  _ast_result=$(jq -nc --arg pattern "$pattern" --arg terminator "$terminator" --argjson body "$body" '{pattern: $pattern, terminator: $terminator, body: $body}')
 }
 
 function ast_echo {
@@ -664,6 +737,7 @@ function macro_import {
 declare -gA _compile_types=()
 declare -gA _compile_imported=()
 declare -ga _compile_commands=()
+declare -g _compile_root=""
 declare -gA _compile_patterns=(
   [int]='^-?[0-9]+$'
   [float]='^-?[0-9]*\.?[0-9]+$'
@@ -746,6 +820,7 @@ function compile {
   _compile_types=()
   _compile_imported=()
   _compile_commands=()
+  _compile_root=""
   _compile_import_dir=${SCRIPPO_IMPORT_DIR:-$(dirname "$path")}
   compile_emit "#!/usr/bin/env bash"
   mapfile -t nodes < <(jq -c '.body[]' <<< "$tree")
@@ -795,6 +870,7 @@ function compile_node {
     if) compile_if "$node" ;;
     for) compile_for "$node" ;;
     while) compile_while "$node" ;;
+    case) compile_case "$node" ;;
     echo) compile_echo "$node" ;;
     declaration) compile_declaration "$node" ;;
     assignment) compile_assignment "$node" ;;
@@ -960,6 +1036,23 @@ function compile_while {
   compile_emit "done"
 }
 
+function compile_case {
+  local node=$1 arms arm pattern terminator
+  compile_expr "$(jq -r .subject <<< "$node")"
+  compile_emit "case $_compile_result in"
+  compile_indent
+  mapfile -t arms < <(jq -c '.arms[]' <<< "$node")
+  for arm in "${arms[@]}"; do
+    compile_read "$arm" '[.pattern, .terminator]' pattern terminator
+    compile_expr "$pattern"
+    compile_emit "$_compile_result)"
+    compile_body "$arm"
+    compile_emit "  $terminator"
+  done
+  compile_dedent
+  compile_emit "esac"
+}
+
 function compile_echo {
   compile_value "$(jq -c .value <<< "$1")" ""
   compile_emit "echo $_compile_result"
@@ -967,7 +1060,7 @@ function compile_echo {
 
 function compile_bash {
   local node=$1 raw
-  local closer_re='^(fi|done|then|do)([[:space:];]|$)'
+  local closer_re='^(fi|done|then|do|esac)([[:space:];]|$)'
   raw=$(jq -r .raw <<< "$node")
   if [[ $raw =~ $closer_re ]]; then
     compile_error "$node" "unexpected '${BASH_REMATCH[1]}': blocks are closed by indentation"
@@ -1037,17 +1130,28 @@ function compile_assignment {
 }
 
 function compile_function {
-  local node=$1 name=$2 type subcommands sub subname
+  local node=$1 name=$2 type subcommands sub subname label
   if [[ -z $name ]]; then
     compile_read "$node" '[.name, .type]' name type
     if [[ $type == command ]] && (( _compile_depth == 0 )); then
       compile_command "$node" "$name"
     fi
   fi
+  label=${name//__/ }
+  if [[ -z $name ]]; then
+    name=_scrippo_root
+    label='${0##*/}'
+  fi
   mapfile -t subcommands < <(jq -c '.body[] | select(.type == "command")' <<< "$node")
 
   for sub in "${subcommands[@]}"; do
-    compile_function "$sub" "${name}__$(jq -r .name <<< "$sub")"
+    subname=$(jq -r .name <<< "$sub")
+    if [[ $name == _scrippo_root ]]; then
+      compile_error "$sub" "commands cannot be nested inside the root command '.()'"
+    elif [[ -z $subname ]]; then
+      compile_error "$sub" "the root command '.()' must be defined at the top level"
+    fi
+    compile_function "$sub" "${name}__$subname"
   done
 
   compile_emit "function $name {"
@@ -1060,7 +1164,7 @@ function compile_function {
     compile_emit "  return"
     compile_emit "fi"
   done
-  compile_params "$node" "${name//__/ }"
+  compile_params "$node" "$label"
   compile_dedent
   compile_body "$node"
   compile_emit "}"
@@ -1273,7 +1377,15 @@ function compile_option {
 }
 
 function compile_command {
-  local node=$1 name=$2
+  local node=$1 name=$2 params
+  if [[ -z $name && -n $_compile_root ]]; then
+    compile_error "$node" "root command '.()' already defined"
+  elif [[ -z $name ]]; then
+    params=$(jq "$_compile_param_jq"'[.params | leaves] | length' <<< "$node")
+    _compile_root=bare
+    (( params == 0 )) || _compile_root=params
+    return 0
+  fi
   if [[ " ${_compile_commands[*]} " == *" $name "* ]]; then
     compile_error "$node" "command '$name' already defined"
   fi
@@ -1282,16 +1394,22 @@ function compile_command {
 
 function compile_dispatch {
   local command
-  if (( ${#_compile_commands[@]} == 0 )); then
+  if [[ -z $_compile_root ]] && (( ${#_compile_commands[@]} == 0 )); then
     return 0
   fi
-  compile_emit "if [[ -z \$1 ]]; then"
-  compile_emit "  echo \"\${0##*/}: command required\" >&2"
-  compile_emit "  echo \"commands: ${_compile_commands[*]}\" >&2"
-  compile_emit "  exit 1"
-  compile_emit "fi"
   compile_emit "case \$1 in"
   compile_indent
+  if [[ -z $_compile_root ]]; then
+    compile_emit "\"\")"
+    compile_emit "  echo \"\${0##*/}: command required\" >&2"
+    compile_emit "  echo \"commands: ${_compile_commands[*]}\" >&2"
+    compile_emit "  exit 1"
+    compile_emit "  ;;"
+  elif [[ $_compile_root == bare ]]; then
+    compile_emit "\"\")"
+    compile_emit "  _scrippo_root"
+    compile_emit "  ;;"
+  fi
   for command in "${_compile_commands[@]}"; do
     compile_emit "$command)"
     compile_emit "  shift"
@@ -1299,9 +1417,15 @@ function compile_dispatch {
     compile_emit "  ;;"
   done
   compile_emit "*)"
-  compile_emit "  echo \"\${0##*/}: unknown command '\$1'\" >&2"
-  compile_emit "  echo \"commands: ${_compile_commands[*]}\" >&2"
-  compile_emit "  exit 1"
+  if [[ $_compile_root == params ]]; then
+    compile_emit "  _scrippo_root \"\$@\""
+  else
+    compile_emit "  echo \"\${0##*/}: unknown command '\$1'\" >&2"
+    if (( ${#_compile_commands[@]} > 0 )); then
+      compile_emit "  echo \"commands: ${_compile_commands[*]}\" >&2"
+    fi
+    compile_emit "  exit 1"
+  fi
   compile_emit "  ;;"
   compile_dedent
   compile_emit "esac"
@@ -1320,6 +1444,7 @@ function scrippo {
   local compile=false
   local noexec=false
   local verbose=false
+  local version=false
   local -a rest=()
   local -a _scrippo_seq=()
   local -a _scrippo_kind=()
@@ -1336,6 +1461,10 @@ function scrippo {
         ;;
       -v|--verbose)
         verbose=true
+        shift
+        ;;
+      --version)
+        version=true
         shift
         ;;
       --)
@@ -1373,11 +1502,9 @@ function scrippo {
     fi
     rest+=("${_scrippo_seq[_scrippo_i]}")
   done
-  if [[ ! ( -n $path ) ]]; then
-    echo "scrippo: <path> is required" >&2
-    exit 1
-  fi
-  if [[ $noexec == true ]]; then
+  if [[ $version == true ]]; then
+    echo $(jq -r '.version' <<< $(cat ./dev/vscode-ext/package.json))
+  elif [[ $noexec == true ]]; then
     bash -n <(compile "$path")
   elif [[ $compile == true ]]; then
     compile "$path"
