adding install command

diff --git a/scrippo b/scrippo
--- a/scrippo
+++ b/scrippo
@@ -388,7 +388,7 @@ function ast_param_item {
     _ast_pos=$(( _ast_pos + 1 ))
   fi
   _ast_result=$(jq -c --argjson repeat "$repeat" '
-    if length == 1 and (.[0].kind == "arg" or .[0].kind == "opt")
+    if length == 1 and (.[0].kind == "arg" or .[0].kind == "opt" or .[0].kind == "rest")
     then .[0] + {optional: true, repeat: (.[0].repeat or $repeat)}
     else {kind: "group", optional: true, repeat: $repeat, params: .}
     end
@@ -397,15 +397,17 @@ function ast_param_item {
 
 function ast_param {
   local token=$1
-  local param_re='^(-{0,2})([a-zA-Z_][a-zA-Z0-9_-]*)(<([^>]*)>)?(\.\.\.)?$'
+  local param_re='^(\*|-{0,2})([a-zA-Z_][a-zA-Z0-9_-]*)(<([^>]*)>)?(\.\.\.)?$'
   local default_re='^([^=]*)=(.*)$'
   [[ $token =~ $param_re ]] || ast_error "invalid parameter '$token'"
-  local dashes=${BASH_REMATCH[1]} name=${BASH_REMATCH[2]} type=${BASH_REMATCH[4]} repeat=false
+  local prefix=${BASH_REMATCH[1]} name=${BASH_REMATCH[2]} type=${BASH_REMATCH[4]} repeat=false
   local kind=arg flag="" default_type=str default="" has_default=false
   [[ -n ${BASH_REMATCH[5]} ]] && repeat=true
-  if [[ -n $dashes ]]; then
+  if [[ $prefix == '*' ]]; then
+    kind=rest
+  elif [[ -n $prefix ]]; then
     kind=opt
-    flag=$dashes$name
+    flag=$prefix$name
     default_type=bool
   fi
   if [[ $type =~ $default_re ]]; then
@@ -682,7 +684,7 @@ def annotate($repeat):
   map(
     if .kind == "group" then .repeat as $r | .params |= annotate($repeat or $r)
     elif .kind == "exclusive" then .options |= annotate($repeat)
-    else . + {array: ((.repeat or $repeat) and .datatype != ["bool"])}
+    else . + {array: (.kind == "rest" or ((.repeat or $repeat) and .datatype != ["bool"]))}
     end
   );
 
@@ -704,6 +706,7 @@ def used:
 def name_of:
   if .kind == "group" then "[" + ([.params[] | name_of] | join(" ")) + "]"
   elif .kind == "exclusive" then [.options[] | name_of] | join(" | ")
+  elif .kind == "rest" then "*\(.name)"
   elif .kind == "arg" then "<\(.name)>"
   else .flag
   end;
@@ -1069,7 +1072,7 @@ function compile_function {
 function compile_params {
   local node=$1 fn=$2 leaves leaf checks check test message
   local kind name flag array multi default base const literals description pattern
-  local position=0 rest=false
+  local position=0 rest=false catchall="" catchall_at=-1 index=0
 
   mapfile -t leaves < <(jq -c "$_compile_param_jq"'.params | annotate(false) | leaves' <<< "$node")
   if (( ${#leaves[@]} == 0 )); then
@@ -1077,8 +1080,25 @@ function compile_params {
   fi
 
   for leaf in "${leaves[@]}"; do
+    compile_read "$leaf" '[.kind, .name]' kind name
+    if [[ $kind == rest ]]; then
+      if [[ -n $catchall ]]; then
+        compile_error "$node" "only one *param is allowed"
+      fi
+      catchall=$name
+      catchall_at=$index
+    fi
+    index=$(( index + 1 ))
+  done
+  if [[ -n $catchall && $catchall_at -ne $(( ${#leaves[@]} - 1 )) ]]; then
+    compile_error "$node" "*$catchall must be the last parameter"
+  fi
+
+  for leaf in "${leaves[@]}"; do
     compile_read "$leaf" '[.kind, .name, .array, .default, .datatype[0]]' kind name array default base
-    if [[ $kind != opt ]]; then
+    if [[ $kind == rest ]]; then
+      compile_emit "local -a $name=()"
+    elif [[ $kind != opt ]]; then
       continue
     elif [[ $array == true ]]; then
       compile_emit "local -a $name=()"
@@ -1089,6 +1109,10 @@ function compile_params {
     fi
   done
 
+  if [[ -n $catchall ]]; then
+    compile_emit "local -a _scrippo_seq=()"
+    compile_emit "local -a _scrippo_kind=()"
+  fi
   compile_emit "local _scrippo_args=()"
   compile_emit "while (( \$# > 0 )); do"
   compile_indent
@@ -1100,23 +1124,53 @@ function compile_params {
       compile_option "$fn" "$name" "$flag" "$array" "$multi" "$base" "$pattern"
     fi
   done
-  compile_emit "--)"
-  compile_emit "  shift"
-  compile_emit "  _scrippo_args+=(\"\$@\")"
-  compile_emit "  break"
-  compile_emit "  ;;"
-  compile_emit "-?*)"
-  compile_emit "  echo \"$fn: unknown option '\$1'\" >&2"
-  compile_emit "  exit 1"
-  compile_emit "  ;;"
-  compile_emit "*)"
-  compile_emit "  _scrippo_args+=(\"\$1\")"
-  compile_emit "  shift"
-  compile_emit "  ;;"
+  if [[ -n $catchall ]]; then
+    compile_emit "--)"
+    compile_emit "  shift"
+    compile_emit "  while (( \$# > 0 )); do"
+    compile_emit "    _scrippo_seq+=(\"\$1\")"
+    compile_emit "    _scrippo_kind+=(arg)"
+    compile_emit "    shift"
+    compile_emit "  done"
+    compile_emit "  ;;"
+    compile_emit "-?*)"
+    compile_emit "  _scrippo_seq+=(\"\$1\")"
+    compile_emit "  _scrippo_kind+=(flag)"
+    compile_emit "  shift"
+    compile_emit "  ;;"
+    compile_emit "*)"
+    compile_emit "  _scrippo_seq+=(\"\$1\")"
+    compile_emit "  _scrippo_kind+=(arg)"
+    compile_emit "  shift"
+    compile_emit "  ;;"
+  else
+    compile_emit "--)"
+    compile_emit "  shift"
+    compile_emit "  _scrippo_args+=(\"\$@\")"
+    compile_emit "  break"
+    compile_emit "  ;;"
+    compile_emit "-?*)"
+    compile_emit "  echo \"$fn: unknown option '\$1'\" >&2"
+    compile_emit "  exit 1"
+    compile_emit "  ;;"
+    compile_emit "*)"
+    compile_emit "  _scrippo_args+=(\"\$1\")"
+    compile_emit "  shift"
+    compile_emit "  ;;"
+  fi
   compile_dedent
   compile_emit "esac"
   compile_dedent
   compile_emit "done"
+
+  if [[ -n $catchall ]]; then
+    compile_emit "local _scrippo_i"
+    compile_emit "for _scrippo_i in \"\${!_scrippo_seq[@]}\"; do"
+    compile_emit "  if [[ \${_scrippo_kind[_scrippo_i]} == arg ]]; then"
+    compile_emit "    _scrippo_args+=(\"\${_scrippo_seq[_scrippo_i]}\")"
+    compile_emit "  fi"
+    compile_emit "done"
+  fi
 
   for leaf in "${leaves[@]}"; do
     compile_read "$leaf" '[.kind, .name, .array, .default]' kind name array default
@@ -1130,7 +1184,9 @@ function compile_params {
       position=$(( position + 1 ))
     fi
   done
-  if [[ $rest == false ]]; then
+  if [[ -n $catchall ]]; then
+    compile_rest "$catchall" "$position" "$rest"
+  elif [[ $rest == false ]]; then
     compile_fail "(( \${#_scrippo_args[@]} > $position ))" "$fn: too many arguments"
   fi
 
@@ -1146,7 +1202,11 @@ function compile_params {
     if [[ $kind == opt && $base == bool ]]; then
       continue
     fi
-    [[ $kind == arg ]] && flag="<$name>"
+    if [[ $kind == rest ]]; then
+      flag="*$name"
+    elif [[ $kind == arg ]]; then
+      flag="<$name>"
+    fi
     if [[ $array == true ]]; then
       compile_type_test '$_scrippo_item' "$base" "$literals"
       [[ -n $_compile_result ]] || continue
@@ -1162,6 +1222,28 @@ function compile_params {
       compile_fail "[[ -n \$$name && $_compile_result ]]" "$fn: $flag expected $description, received '\$$name'"
     fi
   done
+}
+
+function compile_rest {
+  local name=$1 skip=$2 takes_all=$3
+  if [[ $takes_all == true ]]; then
+    compile_emit "for _scrippo_i in \"\${!_scrippo_seq[@]}\"; do"
+    compile_emit "  if [[ \${_scrippo_kind[_scrippo_i]} == flag ]]; then"
+    compile_emit "    $name+=(\"\${_scrippo_seq[_scrippo_i]}\")"
+    compile_emit "  fi"
+    compile_emit "done"
+  elif (( skip == 0 )); then
+    compile_emit "$name=(\"\${_scrippo_seq[@]}\")"
+  else
+    compile_emit "local _scrippo_seen=0"
+    compile_emit "for _scrippo_i in \"\${!_scrippo_seq[@]}\"; do"
+    compile_emit "  if [[ \${_scrippo_kind[_scrippo_i]} == arg ]] && (( _scrippo_seen < $skip )); then"
+    compile_emit "    _scrippo_seen=\$(( _scrippo_seen + 1 ))"
+    compile_emit "    continue"
+    compile_emit "  fi"
+    compile_emit "  $name+=(\"\${_scrippo_seq[_scrippo_i]}\")"
+    compile_emit "done"
+  fi
 }
 
 function compile_option {
@@ -1203,6 +1285,11 @@ function compile_dispatch {
   if (( ${#_compile_commands[@]} == 0 )); then
     return 0
   fi
+  compile_emit "if [[ -z \$1 ]]; then"
+  compile_emit "  echo \"\${0##*/}: command required\" >&2"
+  compile_emit "  echo \"commands: ${_compile_commands[*]}\" >&2"
+  compile_emit "  exit 1"
+  compile_emit "fi"
   compile_emit "case \$1 in"
   compile_indent
   for command in "${_compile_commands[@]}"; do
@@ -1213,6 +1300,7 @@ function compile_dispatch {
   done
   compile_emit "*)"
   compile_emit "  echo \"\${0##*/}: unknown command '\$1'\" >&2"
+  compile_emit "  echo \"commands: ${_compile_commands[*]}\" >&2"
   compile_emit "  exit 1"
   compile_emit "  ;;"
   compile_dedent
@@ -1232,6 +1320,9 @@ function scrippo {
   local compile=false
   local noexec=false
   local verbose=false
+  local -a rest=()
+  local -a _scrippo_seq=()
+  local -a _scrippo_kind=()
   local _scrippo_args=()
   while (( $# > 0 )); do
     case $1 in
@@ -1249,38 +1340,49 @@ function scrippo {
         ;;
       --)
         shift
-        _scrippo_args+=("$@")
-        break
+        while (( $# > 0 )); do
+          _scrippo_seq+=("$1")
+          _scrippo_kind+=(arg)
+          shift
+        done
         ;;
       -?*)
-        echo "scrippo: unknown option '$1'" >&2
-        exit 1
+        _scrippo_seq+=("$1")
+        _scrippo_kind+=(flag)
+        shift
         ;;
       *)
-        _scrippo_args+=("$1")
+        _scrippo_seq+=("$1")
+        _scrippo_kind+=(arg)
         shift
         ;;
     esac
   done
+  local _scrippo_i
+  for _scrippo_i in "${!_scrippo_seq[@]}"; do
+    if [[ ${_scrippo_kind[_scrippo_i]} == arg ]]; then
+      _scrippo_args+=("${_scrippo_seq[_scrippo_i]}")
+    fi
+  done
   local path=${_scrippo_args[0]}
-  if (( ${#_scrippo_args[@]} > 1 )); then
-    echo "scrippo: too many arguments" >&2
-    exit 1
-  fi
+  local _scrippo_seen=0
+  for _scrippo_i in "${!_scrippo_seq[@]}"; do
+    if [[ ${_scrippo_kind[_scrippo_i]} == arg ]] && (( _scrippo_seen < 1 )); then
+      _scrippo_seen=$(( _scrippo_seen + 1 ))
+      continue
+    fi
+    rest+=("${_scrippo_seq[_scrippo_i]}")
+  done
   if [[ ! ( -n $path ) ]]; then
     echo "scrippo: <path> is required" >&2
     exit 1
   fi
-  echo "path: $path"
-  echo "compile: $compile"
-  echo "noexec: $noexec"
-  echo "verbose: $verbose"
   if [[ $noexec == true ]]; then
     bash -n <(compile "$path")
   elif [[ $compile == true ]]; then
     compile "$path"
   else
-    bash -c "$(compile "$path")"
+    bash -c "$(compile "$path")" "$path" "${rest[@]}"
   fi
 }
 
